# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Albert Yerman
email: ahyerman@umich.edu
description: >
  Welcome to my site! My name is Albert Yerman. I am a junior studying
  Computer Science Engineering at the University of Michigan. When I'm not
  programming I like to run or ski.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  ahyerman
linkedin_username: albertyerman

# Build settings
markdown: kramdown
